# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Utils 3 - [Lint, Test & Build]

on:
  push:
    paths:
      - "packages/utils-3/**"
      - "packages/tsconfig/**"
      - "packages/lint-config/**"
      - ".github/workflows/utils-3-build.yml"

jobs:
  lint:
    name: "Step - Lint"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn workspace @avelino-samba/utils-3 install --frozen-lockfile

      - name: Check linting
        run: yarn workspace @avelino-samba/utils-3 prettier:check

  test:
    name: "Step - Test"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: yarn workspace @avelino-samba/utils-3 install --frozen-lockfile

      - name: Check tests
        run: yarn workspace @avelino-samba/utils-3 test

  build:
    name: "Step - Build"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: yarn workspace @avelino-samba/utils-3 install --frozen-lockfile

      - name: Build
        run: yarn workspace @avelino-samba/utils-3 build
